services:
    app:
        build:
            context: .
            target: development
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        volumes:
            - .:/app
        env_file:
            - .env

    web:
        build:
            context: .
            target: development
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        ports:
            - 4567:4567
        volumes:
            - .:/app
        env_file:
            - .env
        command:
            - bundle
            - exec
            - puma
            - -b
            - "tcp://0.0.0.0:4567"

    js:
        build:
            context: .
            target: development
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        volumes:
            - .:/app
        env_file:
            - .env
        command:
            - npm
            - run
            - watch:js

    css:
        build:
            context: .
            target: development
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        volumes:
            - .:/app
        env_file:
            - .env
        command:
            - npm
            - run
            - watch:css
